### ISSUE TITLE
Dokumenty předělat z localu na Google Drive

### ISSUE THREAD

**Issue by danisik** [martin1400cz/managed_docu_familiarization#4]

**Comment by martin1400cz** [comment]
S tímto bodem budou trochu potíže. Udělal jsem rešerži ohledně dostupnosti API pro připojení ke Google Drive, popřípadně Microsoft One Drive a obě služby jsou placené a univerzita mi k nim nedala přístup. Zkusím se porozhlédnout o dalších možnostech, popřípadně využít zkušební verzi těchto služeb. Google Drive potřebuje přístup ke Google cloud - nemám z univerzity přístup a One Drive potřebuje Active Directory přes Azura portal (resp. Microsoft Entra ID) a tam také nemám přístup.

**Comment by danisik** [comment]
Prozatím bych neřešil získávání souborů z OneDrive, ale bohatě postačí nahrát soubory na Google Drive a pouze pracovat s jejich odkazem, který následně **ručně** vložíš do databáze a zobrazíš u daného dokumentu v aplikaci.

**Comment by danisik** [comment]
Dopřidat link do view, a jinak vše hotovo

**Comment by danisik** [comment]
Done
